import 'react-toastify/dist/ReactToastify.css';
import "@/styles/globals.css"
import type { Metadata } from "next";
import { Noto_Sans_Thai } from 'next/font/google';
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/utils/authOptions";
import Layout from '@/containers/Layout';

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const notoSansThai = Noto_Sans_Thai({
    subsets: ['thai']
});

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    const session = await getServerSession(authOptions);

    return (
        <html lang="th">
            <body className={notoSansThai.className}>
                <Layout session={session}>
                    {children}
                </Layout>
            </body>
        </html>
    );
}
